# Generated by Django 3.2.25 on 2024-07-31 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='sentiment',
        ),
        migrations.AlterField(
            model_name='entry',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(default='', max_length=150),
        ),
    ]
