# Generated by Django 3.2.25 on 2025-04-04 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_entry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='blob_sentiment',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='entry',
            name='emotions',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='entry',
            name='sentiment',
            field=models.FloatField(default=0),
        ),
    ]
