# Generated by Django 3.2.25 on 2025-04-04 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_auto_20250404_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='blob_sentiment',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name='entry',
            name='emotions',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name='entry',
            name='sentiment',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
